apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerinformation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web_app
  template:
    metadata:
      labels:
        app: web_app
    spec:
      containers:
        - name: web_app
          image: shubh291998/webapp-repo:1.0
          ports:
            - containerPort: 8080
