apiVersion: v1
kind: Service
metadata:
  name: customerinformation-nodeport
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
